/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <CapSense.h>
#include <CapSense_CSHL.h>
#include <CapSense_TunerHelper.h>
#include <CapSense_SMS.h>
#include <P0_0_PWM_R.h>
#include <P0_0_PWM_R_aliases.h>
#include <P2_0_Distance.h>
#include <P2_0_Distance_aliases.h>
#include <ADC_SAR_Seq.h>
#include <P2_1_Temp.h>
#include <P2_1_Temp_aliases.h>
#include <P2_4_PhaseA_R.h>
#include <P2_4_PhaseA_R_aliases.h>
#include <P2_5_PhaseB_R.h>
#include <P2_5_PhaseB_R_aliases.h>
#include <P2_6_PhaseA_L.h>
#include <P2_6_PhaseA_L_aliases.h>
#include <P2_7_PhaseB_L.h>
#include <P2_7_PhaseB_L_aliases.h>
#include <QuadDec_R.h>
#include <QuadDec_L.h>
#include <Clock_QuadDec.h>
#include <Clock_PWM.h>
#include <PWM_Motor_R.h>
#include <PWM_Motor_L.h>
#include <P0_2_PWM_L.h>
#include <P0_2_PWM_L_aliases.h>
#include <Port1_LineSensor.h>
#include <Port1_LineSensor_aliases.h>
#include <Status_Reg_LineSensor.h>
#include <P0_1_DIR_R.h>
#include <P0_1_DIR_R_aliases.h>
#include <P0_3_DIR_L.h>
#include <P0_3_DIR_L_aliases.h>
#include <P2_2_VBatDiv.h>
#include <P2_2_VBatDiv_aliases.h>
#include <SysTimers.h>
#include <P0_7_Button.h>
#include <P0_7_Button_aliases.h>
#include <P4_0_Debug.h>
#include <P4_0_Debug_aliases.h>
#include <P4_1_RedLED.h>
#include <P4_1_RedLED_aliases.h>
#include <P2_3_AnalogIn.h>
#include <P2_3_AnalogIn_aliases.h>
#include <CapSense_CSD_Clk1.h>
#include <CapSense_CSD_Clk2.h>
#include <CapSense_Sns.h>
#include <CapSense_Sns_aliases.h>
#include <ADC_SAR_Seq_intClock.h>
#include <ADC_SAR_Seq_IRQ.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

