/*******************************************************************************
 * File Name: project.h
 * PSoC Creator 3.0
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <P1_6_RedLED.h>
#include <P1_6_RedLED_aliases.h>
#include <Clock_PWM.h>
#include <PWM_B.h>
#include <PWM_G.h>
#include <SW2_PlayMode.h>
#include <SW2_PlayMode_aliases.h>
#include <PWM_R.h>
#include <P0_3_BlueLED.h>
#include <P0_3_BlueLED_aliases.h>
#include <CapSense_CSD.h>
#include <CapSense_CSD_CSHL.h>
#include <CapSense_CSD_TunerHelper.h>
#include <UART.h>
#include <UART_SPI_UART.h>
#include <UART_PINS.h>
#include <UART_SPI_UART_PVT.h>
#include <UART_PVT.h>
#include <P0_2_GreenLED.h>
#include <P0_2_GreenLED_aliases.h>
#include <PlayMode_ISR.h>
#include <PWM_Tone.h>
#include <Pitch_Clock.h>
#include <P2_0_Speaker.h>
#include <P2_0_Speaker_aliases.h>
#include <PWM_Tone_Mix.h>
#include <Clock_1.h>
#include <CapSense_CSD_SenseClk.h>
#include <CapSense_CSD_SampleClk.h>
#include <CapSense_CSD_Sns_aliases.h>
#include <UART_rx.h>
#include <UART_rx_aliases.h>
#include <UART_SCBCLK.h>
#include <UART_tx.h>
#include <UART_tx_aliases.h>
#include <core_cm0_psoc4.h>
#include <core_cm0.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cyPm.h>
#include <cytypes.h>
#include <cypins.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

